version: "3"

services:
  web:
    image: php:7.2-apache
    restart: 'always'
    depends_on:
      - mariadb
    ports:
      - 80:80
    links:
      - mariadb
    volumes:
      - ./src:/var/www/html
  mariadb:
    image: mariadb:latest
    restart: 'always'
    volumes: 
      - ./data:/var/lib/mysql/data
      - ./logs:/var/lib/mysql/logs
      - ./conf:/etc/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iawdb
      MYSQL_USER: iawusr
      MYSQL_PASSWORD: iawpwd
  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on: 
      - mariadb